### ISSUE TITLE
most info boxes in the metadata browser do not show URIs

### ISSUE THREAD

**Issue by paulopinheiro1234** [paulopinheiro1234/hadatac#36]
Most metadata browser info boxes do not show the URI of the resource been shown. Ideally, every info box would not only show the link but would be an actual href link pointing to the URI.

In the process of implementing these links, t would be nice to verify if uris used in the Jefferson Project's knowledge base are dereferenceable.

**Comment by chastk** [comment]
Fixed mostly in commit cefa14ecc0a7978f6b96eec1197a84701b4b3358. OBOE entities (or anything else without an rdfs:label) still display strangely due to the changes to the pretty printing function, but all of the sensor network entities are fine now. I gathered that there will be a reimplementation of the renderings of the metadata tables soon, with the API coming into use.
